### PR TITLE
Remove exclusions list to index all buckets, even the meta-buckets

### PR DESCRIPTION
**Pull request by gpailler**
With the introduction of the new ["Distinct manifests only"](https://github.com/ScoopInstaller/scoopinstaller.github.io/issues/58), we can now index all the manifests, even the meta-buckets.
Related to https://github.com/ScoopInstaller/Scoop/discussions/5440

### CODE REVIEW

**Comment by gpailler** [comment]
The manifests from the meta-buckets are supposed to be filtered out by the "Distinct manifests only" option. With this option, only the original manifest is supposed to be displayed (based on name/version + commit date).
Do you have examples of original manifests filtered out so I can investigate?

**Comment by HUMORCE** [comment]
i need some time

**Comment by HUMORCE** [comment]
> Do you have examples of original manifests filtered out so I can investigate?

https://github.com/HUMORCE/nuke/blob/master/bucket/jc.json

I searched for some other apps before, i forget exactly which, but this situation exists.

**Comment by gpailler** [comment]
In this example, the manifest from https://github.com/aliesbelik/poldi/blob/main/bucket/jc.json was committed before https://github.com/HUMORCE/nuke/blob/master/bucket/jc.json and that's the reason why your manifest is flagged as a duplicate.

**Comment by HUMORCE** [comment]
Commonly, buckets do not contains duplicate manifests with the offical buckets, unless manifests that made some changes. but meta-bucket just copies manfiests of offical buckets and 3rd-party buckets to one repo.

`jc in HUMORCE/nuke` duplicate with `jc in aliesbelik/poldi`, then how about `jc in lzwme/scoop-proxy-cn`? its download url? idk

**Comment by gpailler** [comment]
Yes the meta-buckets just copy manifests from original buckets and the duplicates add noise to the search results. But they exist and are probably used by several people. The solution I found is to filter out the duplicates and to display only the first occurence of a manifest when "Distinct manifests only" is ticked.

In the example of the "jc" program, the first occurence is the "aliesbelik/poldi" bucket (duplicates are identified by their name+version), then the one in "HUMORCE/nuke" and then 3 well known meta-buckets: https://scoop.sh/#/apps?q=jc+1.23.3+-aoks+-picker+-jcli+-jc_+-jc64+-jcef&dm=false&o=false

**Pull request merged**
